import type { EditorThemeClasses } from "lexical"

export const editorTheme: EditorThemeClasses = {
  paragraph: "mb-0.5 last:mb-0",
  heading: {
    h1: "scroll-m-20 text-2xl font-semibold tracking-tight mt-4 mb-2 first:mt-0",
    h2: "scroll-m-20 text-xl font-semibold tracking-tight mt-4 mb-2 first:mt-0",
    h3: "scroll-m-20 text-lg font-semibold tracking-tight mt-3 mb-1.5 first:mt-0",
    h4: "scroll-m-20 text-base font-semibold tracking-tight mt-3 mb-1 first:mt-0",
    h5: "scroll-m-20 text-sm font-semibold tracking-tight mt-2 mb-1 first:mt-0",
    h6: "scroll-m-20 text-xs font-semibold uppercase tracking-widest mt-2 mb-1 first:mt-0",
  },
  text: {
    bold: "font-semibold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "rounded bg-muted px-1.5 py-0.5 font-mono text-[0.8em]",
    highlight: "bg-amber-200/70 dark:bg-amber-600/50 rounded-sm px-0.5",
    superscript: "text-[0.7em] align-super leading-none",
    subscript: "text-[0.7em] align-sub leading-none",
  },
  list: {
    ul: "list-disc list-outside ml-5 mb-1",
    ol: "list-decimal list-outside ml-5 mb-1",
    listitem: "py-0.5 pl-1",
    nested: {
      listitem: "ml-5",
    },
    checklist: "list-none ml-0",
    listitemChecked:
      "line-through opacity-50 relative pl-6 before:absolute before:left-0 before:top-1 before:size-4 before:rounded before:border before:border-border before:bg-primary before:content-['']",
    listitemUnchecked:
      "relative pl-6 before:absolute before:left-0 before:top-1 before:size-4 before:rounded before:border before:border-border before:bg-background before:content-['']",
  },
  quote:
    "border-l-2 border-border pl-3 text-muted-foreground my-2 italic first:mt-0",
  code: "block rounded-md bg-muted p-3 font-mono text-sm my-2 overflow-x-auto whitespace-pre",
  codeHighlight: {
    atrule: "text-violet-500 dark:text-violet-400",
    attr: "text-emerald-600 dark:text-emerald-400",
    boolean: "text-orange-500",
    builtin: "text-violet-500 dark:text-violet-400",
    cdata: "text-muted-foreground",
    char: "text-emerald-600 dark:text-emerald-400",
    class: "text-yellow-600 dark:text-yellow-400",
    "class-name": "text-yellow-600 dark:text-yellow-400",
    comment: "text-muted-foreground italic",
    constant: "text-orange-500",
    deleted: "text-destructive",
    doctype: "text-muted-foreground",
    entity: "text-orange-500",
    function: "text-sky-600 dark:text-sky-400",
    important: "text-destructive",
    inserted: "text-emerald-600 dark:text-emerald-400",
    keyword: "text-violet-600 dark:text-violet-400",
    namespace: "text-muted-foreground",
    number: "text-orange-500",
    operator: "text-muted-foreground",
    prolog: "text-muted-foreground",
    property: "text-sky-500 dark:text-sky-400",
    punctuation: "text-muted-foreground",
    regex: "text-emerald-600 dark:text-emerald-400",
    selector: "text-emerald-600 dark:text-emerald-400",
    string: "text-emerald-600 dark:text-emerald-400",
    symbol: "text-violet-500",
    tag: "text-sky-600 dark:text-sky-400",
    url: "text-sky-600 underline dark:text-sky-400",
    variable: "text-orange-400",
  },
  link: "text-primary underline underline-offset-4 cursor-pointer hover:text-primary/80",
  hr: "my-3 border-t border-border cursor-pointer",
  hrSelected: "outline outline-2 outline-offset-2 outline-ring",
  hashtag: "bg-muted rounded px-1",
  mark: "bg-yellow-200/50 dark:bg-yellow-800/50 rounded",
  markOverlap: "bg-yellow-200/80 dark:bg-yellow-800/80 rounded",
  table: "border-collapse w-full my-3 table-fixed",
  tableRow: "",
  tableCell:
    "border border-border px-3 py-2 text-sm align-top relative outline-none",
  tableCellHeader:
    "border border-border px-3 py-2 text-sm font-semibold bg-muted align-top",
}
